### ISSUE TITLE
VIC-20 version?

### ISSUE THREAD

**Issue by jj-0** [T-Pau/Anykey#1]
Hi, I find these programs extremely useful in keyboard/joystick mapping for running VICE on THE64 Min/Maxi. I've recommended them on the [THE64 community forum](https://thec64community.online/post/7378/thread).
Is there any chance of you producing a VIC-20 version? Is that a difficult thing to do or relatively easy?

**Comment by dillof** [comment]
It is planned, but I can't say when I'll get to it.

The VIC-20 does not have raster line interrupts, which I use to get the display looking the way I want. Timer interrupts can be used as a workaround, but I've never tried that, so that will take some time. Otherwise, it should be pretty straightforward.

**Comment by jj-0** [comment]
Cool, thanks :-)
